version: "3.7"
services:
  postgres:
    image: postgis/postgis:14-master
    command: -c config_file='/var/lib/postgresql/postgresql.conf'
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/postgresql.conf:/var/lib/postgresql/postgresql.conf
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql